[workspace]
authors = ["Mathew Biddle"]
channels = ["conda-forge"]
name = "Western Indian Ocean Workshop"
platforms = ["win-64", "linux-64", "osx-64"]
version = "1.0.0"

[tasks]
pdf = "jupyter nbconvert Western-Indian-Ocean-Workshop-ioos_qc-demo.ipynb --output-dir=./docs --to pdf --SlidesExporter.reveal_theme=simple --SlidesExporter.theme=light --SlidesExporter.reveal_scroll=True --SlidesExporter.reveal_transition=slide --SlidesExporter.reveal_number=c/t"
tectonic = "jupyter nbconvert Western-Indian-Ocean-Workshop-ioos_qc-demo.ipynb --output-dir=./docs --to pdf --SlidesExporter.reveal_theme=simple --SlidesExporter.theme=light --SlidesExporter.reveal_scroll=True --SlidesExporter.reveal_transition=slide --SlidesExporter.reveal_number=c/t --config=jupyter_nbconvert_config.py"
webpdf = "jupyter nbconvert Western-Indian-Ocean-Workshop-ioos_qc-demo.ipynb --output-dir=./docs --to webpdf --SlidesExporter.reveal_theme=simple --SlidesExporter.theme=light --SlidesExporter.reveal_scroll=True --SlidesExporter.reveal_transition=slide --SlidesExporter.reveal_number=c/t"

[dependencies]
python = "3.10.*"
cf_xarray = ">=0.10.6,<0.11"
ioos_qc = ">=2.2.1,<3"
jupyter = ">=1.1.1,<2"
matplotlib-base = ">=3.10.3,<4"
pandas = ">=2.3.1,<3"
xarray = ">=2025.6.1,<2026"
netcdf4 = ">=1.7.2,<2"
playwright = ">=1.54.1,<2"
playwright-python = ">=1.54.0,<2"
tectonic = ">=0.15.0,<0.16"

[target.win-64.host-dependencies]
miktex = ">=24.4,<25"

[target.linux-64.host-dependencies]
texlive-core = ">=20230313,<20230314"

[target.osx-64.host-dependencies]
texlive-core = ">=20230313,<20230314"
